### ISSUE TITLE
Support for Elasticsearch 6.0

### ISSUE THREAD

**Issue by llonchj** [fabric8io/elasticsearch-cloud-kubernetes#110] opened 2017-11-21 19:09 UTC

**Comment by monotek** [comment] 2018-01-04 15:08
6.1

**Comment by RecursionTaoist** [comment] 2018-02-07 09:20
6.1.1

**Comment by xuhao318** [comment] 2018-02-22 21:37
error when install 6.1.1 plugin
`./elasticsearch-plugin install io.fabric8:elasticsearch-cloud-kubernetes:6.1.2
-> Downloading io.fabric8:elasticsearch-cloud-kubernetes:6.1.2 from maven central
Exception in thread "main" java.io.FileNotFoundException: https://repo1.maven.org/maven2/io/fabric8/elasticsearch-cloud-kubernetes/6.1.2/elasticsearch-cloud-kubernetes-6.1.2.zip
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1944)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1939)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1938)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1508)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
	at org.elasticsearch.plugins.InstallPluginCommand.downloadZip(InstallPluginCommand.java:334)
	at org.elasticsearch.plugins.InstallPluginCommand.downloadZipAndChecksum(InstallPluginCommand.java:379)
	at org.elasticsearch.plugins.InstallPluginCommand.download(InstallPluginCommand.java:239)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:221)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:212)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:75)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
	at org.elasticsearch.cli.Command.main(Command.java:90)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:48)
Caused by: java.io.FileNotFoundException: https://repo1.maven.org/maven2/io/fabric8/elasticsearch-cloud-kubernetes/6.1.2/elasticsearch-cloud-kubernetes-6.1.2.zip
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1890)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:3000)
	at java.net.URLConnection.getHeaderFieldLong(URLConnection.java:629)
	at java.net.URLConnection.getContentLengthLong(URLConnection.java:501)
	at java.net.URLConnection.getContentLength(URLConnection.java:485)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getContentLength(HttpsURLConnectionImpl.java:407)
	at org.elasticsearch.plugins.InstallPluginCommand.downloadZip(InstallPluginCommand.java:333)
	... 10 more
`

**Comment by rchernobelskiy** [comment] 2018-02-27 21:48
Looks like the builds pushing to the maven repo have been broken for awhile, should be a simple fix though:
https://ci.fabric8.io/view/release%20builds/job/elasticsearch-cloud-kubernetes-release/

**Comment by jcantrill** [comment] 2018-02-28 15:05
@maxandersen This is the same issue I had with the a few other fabric repos.  There is no one who is maintaining the release jobs.  I resolved by posting releases to Github directly but we should get someone to take ownership ASAP

**Comment by prune998** [comment] 2018-03-13 11:12
Still broken :(

**Comment by jcantrill** [comment] 2018-04-11 13:11
@llonchj @rchernobelskiy @prune998  Does this resolve your needs for the time being? https://github.com/fabric8io/elasticsearch-cloud-kubernetes/releases/tag/elasticsearch-cloud-kubernetes-6.1.3

**Comment by prune998** [comment] 2018-04-11 13:15
I would say yes... still have to try it :)

**Comment by jcantrill** [comment] 2018-04-19 14:00
6.2.3.1 of the plugin released through a proper release workflow.  Closing this issue.  Please open a new issue with the desired ES compatibility version if others are needed.

**Closed by jcantrill** 2018-04-19 14:00 UTC
